version: '3.8'
services:
  api:
    image: kubedevio/pedelogo-catalogo:v1.0.0
    ports:
      - "8080:80"
    networks:
      - pedelogo
    depends_on:
      - pedelogo-mongodb
    environment:
      Mongo__Host: "pedelogo-mongodb"
      Mongo__User: "mongouser"
      Mongo__Password: "mongopwd"
      Mongo__Port: "27017"
      Mongo__Database: "admin"
    
  pedelogo-mongodb:
    image: mongo:4.1
    networks:
      - pedelogo
    environment:
      MONGO_INIT_ROOT_USERNAME: mongouser
      MONGO_INIT_ROOT_PASSWORD: mongopwd

  mongoexporter:
    image: fabricioveronez/mongo_exporter
    ports:
      - "9216:9216"
    networks:
      - pedelogo
    depends_on:
      - pedelogo-mongodb
    environment:
      MONGODB_URI: "mongodb://mongouser:mongopwd@pedelogo-mongodb:27017"

  prometheus:
    image: prom/prometheus:v2.24.1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - api
    networks:
      - pedelogo

networks:
  pedelogo:
    driver: bridge